language: node_js
node_js:
  - '12'
script: yarn install && yarn test:nowatch && yarn build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: main
